version: "3"
  
services:
  nginx:
    image: nginx:1.17.10
    container_name: zinzaraNginx
    ports:
      - "80:80"
    volumes:
      - ./zinzaraServer:/zinzaraServer
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  web:
    build: .
    container_name: zinzaraWeb
    depends_on:
      - db
